SELECT set_config('silkroad.cloudfront_host', 'd11inahteu3mwm.cloudfront.net', false);

INSERT INTO silkroad.cities (name)
VALUES
    ('Ankrahmun'),
    ('Carlin'),
    ('Darashia'),
    ('Edron'),
    ('Liberty Bay'),
    ('Port Hope'),
    ('Svargrond')
ON CONFLICT (name) DO NOTHING;

INSERT INTO silkroad.quests (name)
VALUES
    ('The Djinn War - Efreet Faction'),
    ('The Djinn War - Marid Faction'),
    ('The Traveling Trader Quest')
ON CONFLICT (name) DO NOTHING;

INSERT INTO silkroad.npcs (name, needs_quest_to_unlock, icon_url)
VALUES
    ('Rashid', TRUE, format('https://%s/icons/npc/Rashid.gif', current_setting('silkroad.cloudfront_host'))),
    ('Nah''Bob', TRUE, format('https://%s/icons/npc/Nah_Bob.gif', current_setting('silkroad.cloudfront_host'))),
    ('Haroun', TRUE, format('https://%s/icons/npc/Haroun.gif', current_setting('silkroad.cloudfront_host'))),
    ('Yaman', TRUE, format('https://%s/icons/npc/Yaman.gif', current_setting('silkroad.cloudfront_host'))),
    ('Alesar', TRUE, format('https://%s/icons/npc/Alesar.gif', current_setting('silkroad.cloudfront_host')))
ON CONFLICT (name) DO UPDATE
SET needs_quest_to_unlock = EXCLUDED.needs_quest_to_unlock,
    icon_url = EXCLUDED.icon_url;

INSERT INTO silkroad.npc_quests (npc_id, quest_id)
SELECT n.id, q.id
FROM (VALUES
    ('Rashid', 'The Traveling Trader Quest'),
    ('Nah''Bob', 'The Djinn War - Marid Faction'),
    ('Haroun', 'The Djinn War - Marid Faction'),
    ('Yaman', 'The Djinn War - Efreet Faction'),
    ('Alesar', 'The Djinn War - Efreet Faction')
) AS v(npc_name, quest_name)
JOIN silkroad.npcs n ON n.name = v.npc_name
JOIN silkroad.quests q ON q.name = v.quest_name
ON CONFLICT (npc_id, quest_id) DO NOTHING;

INSERT INTO silkroad.npc_locations (npc_id, city_id, coord_x, coord_y, coord_z, weekday)
SELECT n.id, c.id, v.coord_x, v.coord_y, v.coord_z, v.weekday
FROM (VALUES
    ('Rashid', 'Svargrond', 125210, 121182, 7, 'Monday'::silkroad.weekday),
    ('Rashid', 'Liberty Bay', 12647, 12867, 7, 'Tuesday'::silkroad.weekday),
    ('Rashid', 'Port Hope', 12765, 127241, 7, 'Wednesday'::silkroad.weekday),
    ('Rashid', 'Ankrahmun', 12945, 128118, 6, 'Thursday'::silkroad.weekday),
    ('Rashid', 'Darashia', 129214, 126227, 7, 'Friday'::silkroad.weekday),
    ('Rashid', 'Edron', 129150, 12457, 6, 'Saturday'::silkroad.weekday),
    ('Rashid', 'Carlin', 12671, 12439, 6, 'Sunday'::silkroad.weekday),
    ('Nah''Bob', 'Darashia', 12980, 1278, 2, NULL),
    ('Haroun', 'Darashia', 12984, 12713, 4, NULL),
    ('Yaman', 'Ankrahmun', 12921, 127108, 2, NULL),
    ('Alesar', 'Ankrahmun', 12924, 127109, 5, NULL)
) AS v(npc_name, city_name, coord_x, coord_y, coord_z, weekday)
JOIN silkroad.npcs n ON n.name = v.npc_name
JOIN silkroad.cities c ON c.name = v.city_name
WHERE NOT EXISTS (
    SELECT 1
    FROM silkroad.npc_locations nl
    WHERE nl.npc_id = n.id
      AND nl.city_id = c.id
      AND nl.coord_x = v.coord_x
      AND nl.coord_y = v.coord_y
      AND nl.coord_z = v.coord_z
      AND nl.weekday IS NOT DISTINCT FROM v.weekday
);

INSERT INTO silkroad.items (name, weight, type, task_deliverable, icon_url)
VALUES
    ('Abyss Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Abyss_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Albino Plate', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Albino_Plate.gif', current_setting('silkroad.cloudfront_host'))),
    ('Amber Staff', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Amber_Staff.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ancient Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Ancient_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ancient Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Ancient_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Angelic Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Angelic_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ankh', 0.00, 'Other', FALSE, format('https://%s/icons/other/Ankh.gif', current_setting('silkroad.cloudfront_host'))),
    ('Assassin Dagger', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Assassin_Dagger.gif', current_setting('silkroad.cloudfront_host'))),
    ('Axe Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Axe_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Bandana', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Bandana.gif', current_setting('silkroad.cloudfront_host'))),
    ('Beastslayer Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Beastslayer_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Beetle Necklace', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Beetle_Necklace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Berserker', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Berserker.gif', current_setting('silkroad.cloudfront_host'))),
    ('Black Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Black_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Blacksteel Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Blacksteel_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Blessed Sceptre', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Blessed_Sceptre.gif', current_setting('silkroad.cloudfront_host'))),
    ('Blue Robe', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Blue_Robe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Bone Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Bone_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Bonebreaker', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Bonebreaker.gif', current_setting('silkroad.cloudfront_host'))),
    ('Bonelord Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Bonelord_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Bonelord Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Bonelord_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Boots of Haste', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Boots_of_Haste.gif', current_setting('silkroad.cloudfront_host'))),
    ('Broadsword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Broadsword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Bronze Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Bronze_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Brutetamer''s Staff', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Brutetamer_s_Staff.gif', current_setting('silkroad.cloudfront_host'))),
    ('Buckle', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Buckle.gif', current_setting('silkroad.cloudfront_host'))),
    ('Butcher''s Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Butcher_s_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Castle Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Castle_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Chain Bolter', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Chain_Bolter.gif', current_setting('silkroad.cloudfront_host'))),
    ('Chaos Mace', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Chaos_Mace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Club Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Club_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Cobra Crown', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Cobra_Crown.gif', current_setting('silkroad.cloudfront_host'))),
    ('Coconut Shoes', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Coconut_Shoes.gif', current_setting('silkroad.cloudfront_host'))),
    ('Composite Hornbow', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Composite_Hornbow.gif', current_setting('silkroad.cloudfront_host'))),
    ('Cranial Basher', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Cranial_Basher.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crocodile Boots', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Crocodile_Boots.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crown Armor', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Crown_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crown Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Crown_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crown Legs', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Crown_Legs.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crown Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Crown_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crusader Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Crusader_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crystal Crossbow', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Crystal_Crossbow.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crystal Mace', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Crystal_Mace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crystal Necklace', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Crystal_Necklace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crystal Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Crystal_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crystal Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Crystal_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Crystalline Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Crystalline_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Daramian Mace', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Daramian_Mace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Daramian Waraxe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Daramian_Waraxe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dark Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Dark_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dark Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Dark_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dark Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Dark_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Death Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Death_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Demon Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Demon_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Demonbone Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Demonbone_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Demonrage Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Demonrage_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Devil Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Devil_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Diamond Sceptre', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Diamond_Sceptre.gif', current_setting('silkroad.cloudfront_host'))),
    ('Divine Plate', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Divine_Plate.gif', current_setting('silkroad.cloudfront_host'))),
    ('Djinn Blade', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Djinn_Blade.gif', current_setting('silkroad.cloudfront_host'))),
    ('Doll', 0.00, 'Other', FALSE, format('https://%s/icons/other/Doll.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dragon Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Dragon_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dragon Lance', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Dragon_Lance.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dragon Necklace', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Dragon_Necklace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dragon Scale Mail', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Dragon_Scale_Mail.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dragon Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Dragon_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dragon Slayer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Dragon_Slayer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dragonbone Staff', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Dragonbone_Staff.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dreaded Cleaver', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Dreaded_Cleaver.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dwarven Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Dwarven_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Dwarven Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Dwarven_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Earth Knight Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Earth_Knight_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Earth Spike Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Earth_Spike_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Earth War Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Earth_War_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Elven Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Elven_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Elvish Bow', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Elvish_Bow.gif', current_setting('silkroad.cloudfront_host'))),
    ('Emerald Bangle', 0.00, 'Other', FALSE, format('https://%s/icons/other/Emerald_Bangle.gif', current_setting('silkroad.cloudfront_host'))),
    ('Energy Knight Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Energy_Knight_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Energy Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Energy_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Energy Spike Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Energy_Spike_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Energy War Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Energy_War_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Epee', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Epee.gif', current_setting('silkroad.cloudfront_host'))),
    ('Fiery Knight Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Fiery_Knight_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Fiery Spike Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Fiery_Spike_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Fiery War Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Fiery_War_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Fire Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Fire_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Fire Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Fire_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Flower Dress', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Flower_Dress.gif', current_setting('silkroad.cloudfront_host'))),
    ('Flower Wreath', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Flower_Wreath.gif', current_setting('silkroad.cloudfront_host'))),
    ('Fur Boots', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Fur_Boots.gif', current_setting('silkroad.cloudfront_host'))),
    ('Furry Club', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Furry_Club.gif', current_setting('silkroad.cloudfront_host'))),
    ('Garlic Necklace', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Garlic_Necklace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Giant Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Giant_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Glacial Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Glacial_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Glacier Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Glacier_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Glacier Kilt', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Glacier_Kilt.gif', current_setting('silkroad.cloudfront_host'))),
    ('Glacier Mask', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Glacier_Mask.gif', current_setting('silkroad.cloudfront_host'))),
    ('Glacier Robe', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Glacier_Robe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Glacier Shoes', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Glacier_Shoes.gif', current_setting('silkroad.cloudfront_host'))),
    ('Glorious Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Glorious_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Gold Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Gold_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Golden Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Golden_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Golden Legs', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Golden_Legs.gif', current_setting('silkroad.cloudfront_host'))),
    ('Goo Shell', 0.00, 'Creature Product', FALSE, format('https://%s/icons/creature_product/Goo_Shell.gif', current_setting('silkroad.cloudfront_host'))),
    ('Greater Garlic Necklace', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Greater_Garlic_Necklace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Griffin Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Griffin_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Guardian Halberd', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Guardian_Halberd.gif', current_setting('silkroad.cloudfront_host'))),
    ('Guardian Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Guardian_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Hailstorm Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Hailstorm_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Hammer of Wrath', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Hammer_of_Wrath.gif', current_setting('silkroad.cloudfront_host'))),
    ('Haunted Blade', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Haunted_Blade.gif', current_setting('silkroad.cloudfront_host'))),
    ('Headchopper', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Headchopper.gif', current_setting('silkroad.cloudfront_host'))),
    ('Heavy Mace', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Heavy_Mace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Heavy Machete', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Heavy_Machete.gif', current_setting('silkroad.cloudfront_host'))),
    ('Heavy Trident', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Heavy_Trident.gif', current_setting('silkroad.cloudfront_host'))),
    ('Helmet of the Lost', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Helmet_of_the_Lost.gif', current_setting('silkroad.cloudfront_host'))),
    ('Heroic Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Heroic_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Hibiscus Dress', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Hibiscus_Dress.gif', current_setting('silkroad.cloudfront_host'))),
    ('Hieroglyph Banner', 0.00, 'Other', FALSE, format('https://%s/icons/other/Hieroglyph_Banner.gif', current_setting('silkroad.cloudfront_host'))),
    ('Horn', 0.00, 'Creature Product', FALSE, format('https://%s/icons/creature_product/Horn.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ice Rapier', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Ice_Rapier.gif', current_setting('silkroad.cloudfront_host'))),
    ('Icy Knight Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Icy_Knight_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Icy Spike Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Icy_Spike_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Icy War Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Icy_War_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Jade Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Jade_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Knight Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Knight_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Knight Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Knight_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Knight Legs', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Knight_Legs.gif', current_setting('silkroad.cloudfront_host'))),
    ('Krimhorn Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Krimhorn_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Lavos Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Lavos_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Leaf Legs', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Leaf_Legs.gif', current_setting('silkroad.cloudfront_host'))),
    ('Leopard Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Leopard_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Leviathan''s Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Leviathan_s_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Life Crystal', 0.00, 'Other', FALSE, format('https://%s/icons/other/Life_Crystal.gif', current_setting('silkroad.cloudfront_host'))),
    ('Life Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Life_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Light Shovel', 0.00, 'Other', FALSE, format('https://%s/icons/other/Light_Shovel.gif', current_setting('silkroad.cloudfront_host'))),
    ('Lightning Boots', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Lightning_Boots.gif', current_setting('silkroad.cloudfront_host'))),
    ('Lightning Headband', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Lightning_Headband.gif', current_setting('silkroad.cloudfront_host'))),
    ('Lightning Legs', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Lightning_Legs.gif', current_setting('silkroad.cloudfront_host'))),
    ('Lightning Pendant', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Lightning_Pendant.gif', current_setting('silkroad.cloudfront_host'))),
    ('Lightning Robe', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Lightning_Robe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Lunar Staff', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Lunar_Staff.gif', current_setting('silkroad.cloudfront_host'))),
    ('Magic Light Wand', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Magic_Light_Wand.gif', current_setting('silkroad.cloudfront_host'))),
    ('Magic Plate Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Magic_Plate_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Magma Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Magma_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Magma Boots', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Magma_Boots.gif', current_setting('silkroad.cloudfront_host'))),
    ('Magma Coat', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Magma_Coat.gif', current_setting('silkroad.cloudfront_host'))),
    ('Magma Legs', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Magma_Legs.gif', current_setting('silkroad.cloudfront_host'))),
    ('Magma Monocle', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Magma_Monocle.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mammoth Fur Cape', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Mammoth_Fur_Cape.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mammoth Fur Shorts', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Mammoth_Fur_Shorts.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mammoth Whopper', 0.00, 'Food', FALSE, format('https://%s/icons/food/Mammoth_Whopper.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mastermind Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Mastermind_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Medusa Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Medusa_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mercenary Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Mercenary_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Might Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Might_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mind Stone', 0.00, 'Other', FALSE, format('https://%s/icons/other/Mind_Stone.gif', current_setting('silkroad.cloudfront_host'))),
    ('Model Ship', 0.00, 'Other', FALSE, format('https://%s/icons/other/Model_Ship.gif', current_setting('silkroad.cloudfront_host'))),
    ('Moonlight Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Moonlight_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Muck Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Muck_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mycological Bow', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Mycological_Bow.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mysterious Fetish', 0.00, 'Other', FALSE, format('https://%s/icons/other/Mysterious_Fetish.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mystic Blade', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Mystic_Blade.gif', current_setting('silkroad.cloudfront_host'))),
    ('Mystic Turban', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Mystic_Turban.gif', current_setting('silkroad.cloudfront_host'))),
    ('Naginata', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Naginata.gif', current_setting('silkroad.cloudfront_host'))),
    ('Necrotic Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Necrotic_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Nightmare Blade', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Nightmare_Blade.gif', current_setting('silkroad.cloudfront_host'))),
    ('Noble Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Noble_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Noble Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Noble_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Norse Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Norse_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Northwind Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Northwind_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Obsidian Lance', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Obsidian_Lance.gif', current_setting('silkroad.cloudfront_host'))),
    ('Onyx Flail', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Onyx_Flail.gif', current_setting('silkroad.cloudfront_host'))),
    ('Onyx Pendant', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Onyx_Pendant.gif', current_setting('silkroad.cloudfront_host'))),
    ('Orb', 0.00, 'Other', FALSE, format('https://%s/icons/other/Orb.gif', current_setting('silkroad.cloudfront_host'))),
    ('Orcish Maul', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Orcish_Maul.gif', current_setting('silkroad.cloudfront_host'))),
    ('Oriental Shoes', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Oriental_Shoes.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ornamented Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Ornamented_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Pair of Iron Fists', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Pair_of_Iron_Fists.gif', current_setting('silkroad.cloudfront_host'))),
    ('Paladin Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Paladin_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Patched Boots', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Patched_Boots.gif', current_setting('silkroad.cloudfront_host'))),
    ('Pharaoh Banner', 0.00, 'Other', FALSE, format('https://%s/icons/other/Pharaoh_Banner.gif', current_setting('silkroad.cloudfront_host'))),
    ('Pharaoh Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Pharaoh_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Phoenix Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Phoenix_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Pirate Boots', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Pirate_Boots.gif', current_setting('silkroad.cloudfront_host'))),
    ('Pirate Hat', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Pirate_Hat.gif', current_setting('silkroad.cloudfront_host'))),
    ('Pirate Knee Breeches', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Pirate_Knee_Breeches.gif', current_setting('silkroad.cloudfront_host'))),
    ('Pirate Shirt', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Pirate_Shirt.gif', current_setting('silkroad.cloudfront_host'))),
    ('Pirate Voodoo Doll', 0.00, 'Other', FALSE, format('https://%s/icons/other/Pirate_Voodoo_Doll.gif', current_setting('silkroad.cloudfront_host'))),
    ('Platinum Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Platinum_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Poison Dagger', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Poison_Dagger.gif', current_setting('silkroad.cloudfront_host'))),
    ('Power Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Power_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Protection Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Protection_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Queen''s Sceptre', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Queen_s_Sceptre.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ragnir Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Ragnir_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Relic Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Relic_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Rift Bow', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Rift_Bow.gif', current_setting('silkroad.cloudfront_host'))),
    ('Rift Crossbow', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Rift_Crossbow.gif', current_setting('silkroad.cloudfront_host'))),
    ('Rift Lance', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Rift_Lance.gif', current_setting('silkroad.cloudfront_host'))),
    ('Rift Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Rift_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ring of Healing', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Ring_of_Healing.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ring of the Sky', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Ring_of_the_Sky.gif', current_setting('silkroad.cloudfront_host'))),
    ('Royal Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Royal_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Royal Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Royal_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ruby Necklace', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Ruby_Necklace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Ruthless Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Ruthless_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Sacred Tree Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Sacred_Tree_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Sapphire Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Sapphire_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('Scarab Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Scarab_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Scarab Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Scarab_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Scimitar', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Scimitar.gif', current_setting('silkroad.cloudfront_host'))),
    ('Serpent Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Serpent_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Shadow Sceptre', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Shadow_Sceptre.gif', current_setting('silkroad.cloudfront_host'))),
    ('Shockwave Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Shockwave_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Silver Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Silver_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Silver Brooch', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Silver_Brooch.gif', current_setting('silkroad.cloudfront_host'))),
    ('Silver Dagger', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Silver_Dagger.gif', current_setting('silkroad.cloudfront_host'))),
    ('Skull Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Skull_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Skull Staff', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Skull_Staff.gif', current_setting('silkroad.cloudfront_host'))),
    ('Skullcracker Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Skullcracker_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Snakebite Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Snakebite_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Spike Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Spike_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('Spiked Squelcher', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Spiked_Squelcher.gif', current_setting('silkroad.cloudfront_host'))),
    ('Springsprout Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Springsprout_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Stealth Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Stealth_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Steel Boots', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Steel_Boots.gif', current_setting('silkroad.cloudfront_host'))),
    ('Stone Skin Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Stone_Skin_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Strange Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Strange_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Strange Talisman', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Strange_Talisman.gif', current_setting('silkroad.cloudfront_host'))),
    ('Swamplair Armor', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Swamplair_Armor.gif', current_setting('silkroad.cloudfront_host'))),
    ('Sword Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Sword_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Taurus Mace', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Taurus_Mace.gif', current_setting('silkroad.cloudfront_host'))),
    ('Tempest Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Tempest_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Terra Amulet', 0.00, 'Amulet', FALSE, format('https://%s/icons/amulet/Terra_Amulet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Terra Boots', 0.00, 'Boots', FALSE, format('https://%s/icons/boots/Terra_Boots.gif', current_setting('silkroad.cloudfront_host'))),
    ('Terra Hood', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Terra_Hood.gif', current_setting('silkroad.cloudfront_host'))),
    ('Terra Legs', 0.00, 'Legs', FALSE, format('https://%s/icons/legs/Terra_Legs.gif', current_setting('silkroad.cloudfront_host'))),
    ('Terra Mantle', 0.00, 'Armor', FALSE, format('https://%s/icons/armor/Terra_Mantle.gif', current_setting('silkroad.cloudfront_host'))),
    ('Terra Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Terra_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Thaian Sword', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Thaian_Sword.gif', current_setting('silkroad.cloudfront_host'))),
    ('The Justice Seeker', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/The_Justice_Seeker.gif', current_setting('silkroad.cloudfront_host'))),
    ('Time Ring', 0.00, 'Ring', FALSE, format('https://%s/icons/ring/Time_Ring.gif', current_setting('silkroad.cloudfront_host'))),
    ('Titan Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Titan_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Tortoise Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Tortoise_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Tower Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Tower_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Underworld Rod', 0.00, 'Rod', FALSE, format('https://%s/icons/rod/Underworld_Rod.gif', current_setting('silkroad.cloudfront_host'))),
    ('Vampire Shield', 0.00, 'Shield', FALSE, format('https://%s/icons/shield/Vampire_Shield.gif', current_setting('silkroad.cloudfront_host'))),
    ('Vile Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/Vile_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('Voodoo Doll', 0.00, 'Other', FALSE, format('https://%s/icons/other/Voodoo_Doll.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Cosmic Energy', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Cosmic_Energy.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Decay', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Decay.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Defiance', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Defiance.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Draconia', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Draconia.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Dragonbreath', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Dragonbreath.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Everblazing', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Everblazing.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Inferno', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Inferno.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Starstorm', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Starstorm.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Voodoo', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Voodoo.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wand of Vortex', 0.00, 'Wand', FALSE, format('https://%s/icons/wand/Wand_of_Vortex.gif', current_setting('silkroad.cloudfront_host'))),
    ('War Axe', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/War_Axe.gif', current_setting('silkroad.cloudfront_host'))),
    ('War Hammer', 0.00, 'Weapon', FALSE, format('https://%s/icons/weapon/War_Hammer.gif', current_setting('silkroad.cloudfront_host'))),
    ('War Horn', 0.00, 'Creature Product', FALSE, format('https://%s/icons/creature_product/War_Horn.gif', current_setting('silkroad.cloudfront_host'))),
    ('Warrior Helmet', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Warrior_Helmet.gif', current_setting('silkroad.cloudfront_host'))),
    ('Witch Hat', 0.00, 'Helmet', FALSE, format('https://%s/icons/helmet/Witch_Hat.gif', current_setting('silkroad.cloudfront_host'))),
    ('Wyvern Fang', 0.00, 'Creature Product', FALSE, format('https://%s/icons/creature_product/Wyvern_Fang.gif', current_setting('silkroad.cloudfront_host')))
ON CONFLICT (name) DO UPDATE
SET weight = EXCLUDED.weight,
    type = EXCLUDED.type,
    task_deliverable = EXCLUDED.task_deliverable,
    icon_url = EXCLUDED.icon_url;

INSERT INTO silkroad.offers (item_id, npc_id, price)
SELECT i.id, n.id, v.price
FROM (VALUES
    ('Ancient Shield', 'Alesar', 900),
    ('Black Shield', 'Alesar', 800),
    ('Bonebreaker', 'Alesar', 10000),
    ('Dark Armor', 'Alesar', 400),
    ('Dark Helmet', 'Alesar', 250),
    ('Dragon Hammer', 'Alesar', 2000),
    ('Dreaded Cleaver', 'Alesar', 15000),
    ('Earth Knight Axe', 'Alesar', 2000),
    ('Energy Knight Axe', 'Alesar', 2000),
    ('Fiery Knight Axe', 'Alesar', 2000),
    ('Giant Sword', 'Alesar', 17000),
    ('Haunted Blade', 'Alesar', 8000),
    ('Icy Knight Axe', 'Alesar', 2000),
    ('Knight Armor', 'Alesar', 5000),
    ('Knight Axe', 'Alesar', 2000),
    ('Knight Legs', 'Alesar', 5000),
    ('Mystic Turban', 'Alesar', 150),
    ('Onyx Flail', 'Alesar', 22000),
    ('Ornamented Axe', 'Alesar', 20000),
    ('Poison Dagger', 'Alesar', 50),
    ('Scimitar', 'Alesar', 150),
    ('Serpent Sword', 'Alesar', 900),
    ('Skull Staff', 'Alesar', 6000),
    ('Strange Helmet', 'Alesar', 500),
    ('Titan Axe', 'Alesar', 4000),
    ('Tower Shield', 'Alesar', 8000),
    ('Vampire Shield', 'Alesar', 15000),
    ('Warrior Helmet', 'Alesar', 5000),
    ('Axe Ring', 'Haroun', 100),
    ('Bronze Amulet', 'Haroun', 50),
    ('Club Ring', 'Haroun', 100),
    ('Elven Amulet', 'Haroun', 100),
    ('Garlic Necklace', 'Haroun', 50),
    ('Greater Garlic Necklace', 'Haroun', 10000),
    ('Life Crystal', 'Haroun', 50),
    ('Magic Light Wand', 'Haroun', 35),
    ('Mind Stone', 'Haroun', 100),
    ('Orb', 'Haroun', 750),
    ('Power Ring', 'Haroun', 50),
    ('Stealth Ring', 'Haroun', 200),
    ('Stone Skin Amulet', 'Haroun', 500),
    ('Sword Ring', 'Haroun', 100),
    ('Wand of Cosmic Energy', 'Haroun', 2000),
    ('Wand of Decay', 'Haroun', 1000),
    ('Wand of Defiance', 'Haroun', 6500),
    ('Wand of Draconia', 'Haroun', 1500),
    ('Wand of Dragonbreath', 'Haroun', 200),
    ('Wand of Everblazing', 'Haroun', 6000),
    ('Wand of Inferno', 'Haroun', 3000),
    ('Wand of Starstorm', 'Haroun', 3600),
    ('Wand of Voodoo', 'Haroun', 4400),
    ('Wand of Vortex', 'Haroun', 100),
    ('Angelic Axe', 'Nah''Bob', 5000),
    ('Blue Robe', 'Nah''Bob', 10000),
    ('Bonelord Shield', 'Nah''Bob', 1200),
    ('Boots of Haste', 'Nah''Bob', 30000),
    ('Broadsword', 'Nah''Bob', 500),
    ('Butcher''s Axe', 'Nah''Bob', 18000),
    ('Crown Armor', 'Nah''Bob', 12000),
    ('Crown Helmet', 'Nah''Bob', 2500),
    ('Crown Legs', 'Nah''Bob', 12000),
    ('Crown Shield', 'Nah''Bob', 8000),
    ('Crusader Helmet', 'Nah''Bob', 6000),
    ('Dragon Lance', 'Nah''Bob', 9000),
    ('Dragon Shield', 'Nah''Bob', 4000),
    ('Earth Spike Sword', 'Nah''Bob', 1000),
    ('Earth War Hammer', 'Nah''Bob', 1200),
    ('Energy Spike Sword', 'Nah''Bob', 1000),
    ('Energy War Hammer', 'Nah''Bob', 1200),
    ('Fiery Spike Sword', 'Nah''Bob', 1000),
    ('Fiery War Hammer', 'Nah''Bob', 1200),
    ('Fire Axe', 'Nah''Bob', 8000),
    ('Fire Sword', 'Nah''Bob', 4000),
    ('Glorious Axe', 'Nah''Bob', 3000),
    ('Guardian Shield', 'Nah''Bob', 2000),
    ('Ice Rapier', 'Nah''Bob', 1000),
    ('Icy Spike Sword', 'Nah''Bob', 1000),
    ('Icy War Hammer', 'Nah''Bob', 1200),
    ('Noble Armor', 'Nah''Bob', 900),
    ('Obsidian Lance', 'Nah''Bob', 500),
    ('Phoenix Shield', 'Nah''Bob', 16000),
    ('Queen''s Sceptre', 'Nah''Bob', 20000),
    ('Royal Helmet', 'Nah''Bob', 30000),
    ('Shadow Sceptre', 'Nah''Bob', 10000),
    ('Spike Sword', 'Nah''Bob', 1000),
    ('Thaian Sword', 'Nah''Bob', 16000),
    ('War Hammer', 'Nah''Bob', 1200),
    ('Abyss Hammer', 'Rashid', 20000),
    ('Albino Plate', 'Rashid', 1500),
    ('Amber Staff', 'Rashid', 8000),
    ('Ancient Amulet', 'Rashid', 200),
    ('Assassin Dagger', 'Rashid', 20000),
    ('Bandana', 'Rashid', 150),
    ('Beastslayer Axe', 'Rashid', 1500),
    ('Beetle Necklace', 'Rashid', 1500),
    ('Berserker', 'Rashid', 40000),
    ('Blacksteel Sword', 'Rashid', 6000),
    ('Blessed Sceptre', 'Rashid', 40000),
    ('Bone Shield', 'Rashid', 80),
    ('Bonelord Helmet', 'Rashid', 7500),
    ('Brutetamer''s Staff', 'Rashid', 1500),
    ('Buckle', 'Rashid', 7000),
    ('Castle Shield', 'Rashid', 5000),
    ('Chain Bolter', 'Rashid', 40000),
    ('Chaos Mace', 'Rashid', 9000),
    ('Cobra Crown', 'Rashid', 50000),
    ('Coconut Shoes', 'Rashid', 500),
    ('Composite Hornbow', 'Rashid', 25000),
    ('Cranial Basher', 'Rashid', 30000),
    ('Crocodile Boots', 'Rashid', 1000),
    ('Crystal Crossbow', 'Rashid', 35000),
    ('Crystal Mace', 'Rashid', 12000),
    ('Crystal Necklace', 'Rashid', 400),
    ('Crystal Ring', 'Rashid', 250),
    ('Crystal Sword', 'Rashid', 600),
    ('Crystalline Armor', 'Rashid', 16000),
    ('Daramian Mace', 'Rashid', 110),
    ('Daramian Waraxe', 'Rashid', 1000),
    ('Dark Shield', 'Rashid', 400),
    ('Death Ring', 'Rashid', 1000),
    ('Demon Shield', 'Rashid', 30000),
    ('Demonbone Amulet', 'Rashid', 32000),
    ('Demonrage Sword', 'Rashid', 36000),
    ('Devil Helmet', 'Rashid', 1000),
    ('Diamond Sceptre', 'Rashid', 3000),
    ('Divine Plate', 'Rashid', 55000),
    ('Djinn Blade', 'Rashid', 15000),
    ('Doll', 'Rashid', 200),
    ('Dragon Scale Mail', 'Rashid', 40000),
    ('Dragon Slayer', 'Rashid', 15000),
    ('Dragonbone Staff', 'Rashid', 3000),
    ('Dreaded Cleaver', 'Rashid', 10000),
    ('Dwarven Armor', 'Rashid', 30000),
    ('Elvish Bow', 'Rashid', 2000),
    ('Emerald Bangle', 'Rashid', 800),
    ('Epee', 'Rashid', 8000),
    ('Flower Dress', 'Rashid', 1000),
    ('Flower Wreath', 'Rashid', 500),
    ('Fur Boots', 'Rashid', 2000),
    ('Furry Club', 'Rashid', 1000),
    ('Glacier Amulet', 'Rashid', 1500),
    ('Glacier Kilt', 'Rashid', 11000),
    ('Glacier Mask', 'Rashid', 2500),
    ('Glacier Robe', 'Rashid', 11000),
    ('Glacier Shoes', 'Rashid', 2500),
    ('Gold Ring', 'Rashid', 8000),
    ('Golden Armor', 'Rashid', 20000),
    ('Golden Legs', 'Rashid', 30000),
    ('Goo Shell', 'Rashid', 4000),
    ('Griffin Shield', 'Rashid', 3000),
    ('Guardian Halberd', 'Rashid', 11000),
    ('Hammer of Wrath', 'Rashid', 30000),
    ('Headchopper', 'Rashid', 6000),
    ('Heavy Mace', 'Rashid', 50000),
    ('Heavy Machete', 'Rashid', 90),
    ('Heavy Trident', 'Rashid', 2000),
    ('Helmet of the Lost', 'Rashid', 2000),
    ('Heroic Axe', 'Rashid', 30000),
    ('Hibiscus Dress', 'Rashid', 3000),
    ('Hieroglyph Banner', 'Rashid', 500),
    ('Horn', 'Rashid', 300),
    ('Jade Hammer', 'Rashid', 25000),
    ('Krimhorn Helmet', 'Rashid', 200),
    ('Lavos Armor', 'Rashid', 16000),
    ('Leaf Legs', 'Rashid', 500),
    ('Leopard Armor', 'Rashid', 1000),
    ('Leviathan''s Amulet', 'Rashid', 3000),
    ('Light Shovel', 'Rashid', 300),
    ('Lightning Boots', 'Rashid', 2500),
    ('Lightning Headband', 'Rashid', 2500),
    ('Lightning Legs', 'Rashid', 11000),
    ('Lightning Pendant', 'Rashid', 1500),
    ('Lightning Robe', 'Rashid', 11000),
    ('Lunar Staff', 'Rashid', 5000),
    ('Magic Plate Armor', 'Rashid', 90000),
    ('Magma Amulet', 'Rashid', 1500),
    ('Magma Boots', 'Rashid', 2500),
    ('Magma Coat', 'Rashid', 11000),
    ('Magma Legs', 'Rashid', 11000),
    ('Magma Monocle', 'Rashid', 2500),
    ('Mammoth Fur Cape', 'Rashid', 6000),
    ('Mammoth Fur Shorts', 'Rashid', 850),
    ('Mammoth Whopper', 'Rashid', 300),
    ('Mastermind Shield', 'Rashid', 50000),
    ('Medusa Shield', 'Rashid', 9000),
    ('Mercenary Sword', 'Rashid', 12000),
    ('Model Ship', 'Rashid', 1000),
    ('Mycological Bow', 'Rashid', 35000),
    ('Mystic Blade', 'Rashid', 30000),
    ('Naginata', 'Rashid', 2000),
    ('Nightmare Blade', 'Rashid', 35000),
    ('Noble Axe', 'Rashid', 10000),
    ('Norse Shield', 'Rashid', 1500),
    ('Onyx Pendant', 'Rashid', 3500),
    ('Orcish Maul', 'Rashid', 6000),
    ('Oriental Shoes', 'Rashid', 15000),
    ('Pair of Iron Fists', 'Rashid', 4000),
    ('Paladin Armor', 'Rashid', 15000),
    ('Patched Boots', 'Rashid', 2000),
    ('Pharaoh Banner', 'Rashid', 1000),
    ('Pharaoh Sword', 'Rashid', 23000),
    ('Pirate Boots', 'Rashid', 3000),
    ('Pirate Hat', 'Rashid', 1000),
    ('Pirate Knee Breeches', 'Rashid', 200),
    ('Pirate Shirt', 'Rashid', 500),
    ('Pirate Voodoo Doll', 'Rashid', 500),
    ('Platinum Amulet', 'Rashid', 2500),
    ('Ragnir Helmet', 'Rashid', 400),
    ('Relic Sword', 'Rashid', 25000),
    ('Rift Bow', 'Rashid', 45000),
    ('Rift Crossbow', 'Rashid', 45000),
    ('Rift Lance', 'Rashid', 30000),
    ('Rift Shield', 'Rashid', 50000),
    ('Ring of the Sky', 'Rashid', 30000),
    ('Royal Axe', 'Rashid', 40000),
    ('Ruby Necklace', 'Rashid', 2000),
    ('Ruthless Axe', 'Rashid', 45000),
    ('Sacred Tree Amulet', 'Rashid', 3000),
    ('Sapphire Hammer', 'Rashid', 7000),
    ('Scarab Amulet', 'Rashid', 200),
    ('Scarab Shield', 'Rashid', 2000),
    ('Shockwave Amulet', 'Rashid', 3000),
    ('Silver Brooch', 'Rashid', 150),
    ('Silver Dagger', 'Rashid', 500),
    ('Skull Helmet', 'Rashid', 40000),
    ('Skullcracker Armor', 'Rashid', 18000),
    ('Spiked Squelcher', 'Rashid', 5000),
    ('Steel Boots', 'Rashid', 30000),
    ('Swamplair Armor', 'Rashid', 16000),
    ('Taurus Mace', 'Rashid', 500),
    ('Tempest Shield', 'Rashid', 35000),
    ('Terra Amulet', 'Rashid', 1500),
    ('Terra Boots', 'Rashid', 2500),
    ('Terra Hood', 'Rashid', 2500),
    ('Terra Legs', 'Rashid', 11000),
    ('Terra Mantle', 'Rashid', 11000),
    ('The Justice Seeker', 'Rashid', 40000),
    ('Tortoise Shield', 'Rashid', 150),
    ('Vile Axe', 'Rashid', 30000),
    ('Voodoo Doll', 'Rashid', 400),
    ('War Axe', 'Rashid', 12000),
    ('War Horn', 'Rashid', 8000),
    ('Witch Hat', 'Rashid', 5000),
    ('Wyvern Fang', 'Rashid', 1500),
    ('Ankh', 'Yaman', 100),
    ('Dragon Necklace', 'Yaman', 100),
    ('Dwarven Ring', 'Yaman', 100),
    ('Energy Ring', 'Yaman', 100),
    ('Glacial Rod', 'Yaman', 6500),
    ('Hailstorm Rod', 'Yaman', 3000),
    ('Life Ring', 'Yaman', 50),
    ('Might Ring', 'Yaman', 250),
    ('Moonlight Rod', 'Yaman', 200),
    ('Muck Rod', 'Yaman', 6000),
    ('Mysterious Fetish', 'Yaman', 50),
    ('Necrotic Rod', 'Yaman', 1000),
    ('Northwind Rod', 'Yaman', 1500),
    ('Protection Amulet', 'Yaman', 100),
    ('Ring of Healing', 'Yaman', 100),
    ('Silver Amulet', 'Yaman', 50),
    ('Snakebite Rod', 'Yaman', 100),
    ('Springsprout Rod', 'Yaman', 3600),
    ('Strange Talisman', 'Yaman', 30),
    ('Terra Rod', 'Yaman', 2000),
    ('Time Ring', 'Yaman', 100),
    ('Underworld Rod', 'Yaman', 4400)
) AS v(item_name, npc_name, price)
JOIN silkroad.items i ON i.name = v.item_name
JOIN silkroad.npcs n ON n.name = v.npc_name
ON CONFLICT (item_id, npc_id) DO UPDATE
SET price = EXCLUDED.price;